AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Skafu - Observability Domain Stack'

Parameters:
  Environment:
    Type: String
    AllowedValues: [development, staging, production]
    Default: development
    Description: Environment name
  
  LogLevel:
    Type: String
    AllowedValues: [DEBUG, INFO, WARN, ERROR]
    Default: INFO
    Description: Lambda function log level
  
  EventBusName:
    Type: String
    Description: Custom EventBridge bus name from shared resources
  
  ErrorBusName:
    Type: String
    Description: Error EventBridge bus name from shared resources
  
  UserPoolId:
    Type: String
    Description: Cognito User Pool ID from shared resources
  
  UserPoolClientId:
    Type: String
    Description: Cognito User Pool Client ID from shared resources
  
  ApiGatewayId:
    Type: String
    Description: API Gateway ID from shared resources
  
  ApiGatewayRootResourceId:
    Type: String
    Description: API Gateway V1 Resource ID from shared resources

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: skafu-observability
        POWERTOOLS_METRICS_NAMESPACE: skafu
        LOG_LEVEL: !Ref LogLevel
        ENVIRONMENT: !Ref Environment
        EVENT_BUS_NAME: !Ref EventBusName
        ERROR_BUS_NAME: !Ref ErrorBusName
        USER_POOL_ID: !Ref UserPoolId
        USER_POOL_CLIENT_ID: !Ref UserPoolClientId
    Tracing: Active
    Layers:
      - !Ref PowertoolsLayer
    Tags:
      Environment: !Ref Environment
      Project: Skafu
      Domain: Observability
      ManagedBy: SAM

Resources:
  # AWS Lambda Powertools Layer
  PowertoolsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'skafu-powertools-${Environment}'
      Description: AWS Lambda Powertools for Python
      ContentUri: ../../shared/layers/powertools/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.12
  
  # API Gateway Resources
  ObservabilityResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayId
      ParentId: !Ref ApiGatewayRootResourceId
      PathPart: 'observability'
  
  
  
  # Lambda Functions
  